/**
 * Test helpers shared by the webview-* test suites.
 *
 * This file is not a *.test.ts file on purpose: it is only ever imported by
 * the test files themselves and is never reached from the production import
 * graph (webpack only follows imports from `src/extension.ts`), so it will
 * not be bundled into the published extension.
 */
import type { WebviewTranslations } from "./webview-html";

/**
 * Returns a fully-populated `WebviewTranslations` object suitable for driving
 * the webview IIFE generators in unit tests. Pass a partial object to override
 * only the fields you care about.
 */
export function makeTr(overrides?: Partial<WebviewTranslations>): WebviewTranslations {
  return {
    locale: "en",
    history: "History",
    threads: "Threads",
    sessions: "Sessions",
    tasks: "Tasks",
    work: "Work",
    newThread: "New Thread",
    compact: "Compact",
    interrupt: "Interrupt",
    toggleHistory: "Toggle History",
    send: "Send",
    inputPlaceholder: "Type a message...",
    initializing: "Initializing...",
    ready: "Ready",
    thinking: "Thinking...",
    streaming: "Streaming...",
    processing: "Processing...",
    error: "Error",
    approvalAwaiting: "Approval Required",
    noConversations: "No conversations",
    threadAttention: "Waiting for your approval or input — click to open",
    noTasks: "No tasks",
    taskCreate: "New Task",
    taskCreateTitle: "Create Task",
    taskCreatePlaceholder: "Describe the background task...",
    taskCreateSubmit: "Create",
    taskRefresh: "Refresh",
    taskDetails: "Details",
    taskOpenThread: "Open Thread",
    taskAttention: "Attention",
    taskNeedsAttention: "Needs attention",
    taskPendingApprovals: "Pending Approvals",
    taskPendingInputs: "Pending Inputs",
    taskContinueInThread: "Continue in thread",
    threadsCountPattern: "{n} threads",
    modelLabel: "Model",
    workspaceLabel: "Workspace",
    loadedThreadPattern: "Loaded: {0}",
    showAllWorkspaces: "Show all workspaces",
    filterCurrentWorkspace: "Current workspace",
    approvalRequired: "Approval required",
    allow: "Allow",
    deny: "Deny",
    thinkingToggle: "Thinking",
    thinkingOpen: "▶ Thinking",
    thinkingClose: "▼ Thinking",
    steerPlaceholder: "Steer the running turn...",
    steerBadge: "steer",
    steerBadgeTitle: "Sent as mid-turn steering",
    modeLabel: "Mode",
    reasoningEffortLabel: "Reasoning",
    welcomeTitle: "CodeWhale",
    welcomeSubtitle: "Your AI coding partner",
    welcomeQuote: "The best way to predict the future is to invent it.",
    welcomeQuoteAuthor: "Alan Kay",
    welcomeSuggestionTitle: "Try asking",
    welcomeSuggestion1: "Explain this code",
    welcomeSuggestion2: "Write a test",
    welcomeSuggestion3: "Find bugs",
    welcomeSuggestion4: "Refactor this",
    noActiveWork: "No active work",
    cancel: "Cancel",
    goal: "Goal",
    checklist: "Checklist",
    strategy: "Strategy",
    cycles: "Cycles",
    coherenceHealthy: "Healthy",
    coherenceGettingCrowded: "Getting crowded",
    coherenceRefreshingContext: "Refreshing context",
    coherenceVerifyingRecentWork: "Verifying recent work",
    coherenceResettingPlan: "Resetting plan",
    completionPct: "0%",
    readyTimedOut: "Ready timed out",
    note: "Note",
    noPreviousMessage: "No previous message",
    justNow: "just now",
    minutesAgoPattern: "{n} min ago",
    hoursAgoPattern: "{n}h ago",
    daysAgoPattern: "{n}d ago",
    commandMode: "/mode",
    commandModel: "/model",
    commandModels: "/models",
    commandReasoning: "/reasoning",
    commandConfig: "/config",
    commandSettings: "/settings",
    commandClear: "/clear",
    commandInterrupt: "/interrupt",
    commandHelp: "/help",
    commandCompact: "/compact",
    commandExit: "/exit",
    commandRename: "/rename",
    commandSave: "/save",
    commandExport: "/export",
    commandContext: "/context",
    commandTokens: "/tokens",
    commandCost: "/cost",
    commandStatus: "/status",
    commandHome: "/home",
    commandWorkspace: "/workspace",
    commandTask: "/task",
    commandJobs: "/jobs",
    commandNote: "/note",
    commandMemory: "/memory",
    commandTrust: "/trust",
    commandVerbose: "/verbose",
    commandTheme: "/theme",
    commandUndo: "/undo",
    commandRetry: "/retry",
    commandShare: "/share",
    commandGoal: "/goal",
    commandSkills: "/skills",
    commandSkill: "/skill",
    commandMcp: "/mcp",
    commandNetwork: "/network",
    commandProvider: "/provider",
    commandQueue: "/queue",
    commandStash: "/stash",
    commandHooks: "/hooks",
    commandSubagents: "/subagents",
    commandAgent: "/agent",
    commandLinks: "/links",
    commandFeedback: "/feedback",
    commandAttach: "/attach",
    commandAnchor: "/anchor",
    commandSessions: "/sessions",
    commandLoad: "/load",
    commandCycles: "/cycles",
    commandCycle: "/cycle",
    commandRecall: "/recall",
    commandRelay: "/relay",
    commandInit: "/init",
    commandLsp: "/lsp",
    commandReview: "/review",
    commandRestore: "/restore",
    commandRlm: "/rlm",
    commandChange: "/change",
    commandCache: "/cache",
    commandProfile: "/profile",
    commandTranslate: "/translate",
    commandSystem: "/system",
    commandEdit: "/edit",
    commandDiff: "/diff",
    commandStatusline: "/statusline",
    commandLogout: "/logout",
    commandNotAvailableInGui: "Not available in GUI",
    attachFiles: "Attach files",
    removeAttachment: "Remove",
    attachedFileCount: "{n} files attached",
    fileNotSupported: "File type not supported",
    changes: "Changes",
    noFileChanges: "No file changes in this session",
    undoUnsupportedTooltip: "Undo not supported",
    retryUnsupportedTooltip: "Retry not supported",
    revertUnsupportedTooltip: "Revert not supported",
    fileCreated: "Created",
    fileDeleted: "Deleted",
    fileModified: "Modified",
    viewDiff: "View Diff",
    viewDiffTooltip: "View file diff",
    openFile: "Open File",
    openFileTooltip: "Open file in editor",
    revertFile: "Revert",
    revertFileTooltip: "Revert file changes",
    fileChanges: "File Changes",
    userInputAwaiting: "Input required",
    searchSessions: "Search",
    searchPlaceholder: "Search sessions...",
    deleteSession: "Delete",
    deleteSessionConfirmTitle: "Delete session?",
    deleteSessionConfirmMessage: 'This will permanently delete the session "{title}". This cannot be undone.',
    deleteSessionConfirmButton: "Delete",
    deleteSessionSuccess: "Session deleted",
    deleteSessionFailed: "Failed to delete session",
    noSearchResults: "No matching sessions",
    // Agent panel
    agents: "Agents",
    noAgentRuns: "No agent runs",
    agentStatusQueued: "Queued",
    agentStatusStarting: "Starting",
    agentStatusRunning: "Running",
    agentStatusWaitingForUser: "Waiting for input",
    agentStatusModelWait: "Waiting for model",
    agentStatusRunningTool: "Running tool",
    agentStatusCompleted: "Completed",
    agentStatusFailed: "Failed",
    agentStatusCancelled: "Cancelled",
    agentStatusInterrupted: "Interrupted",
    agentObjective: "Objective",
    agentModel: "Model",
    agentSteps: "Steps",
    agentResult: "Result",
    agentError: "Error",
    agentRole: "Role",
    agentArtifacts: "Artifacts",
    agentUsage: "Token usage",
    agentSpawned: "Spawned",
    agentDelegating: "Delegating",
    agentFanout: "Fan-out",
    // Fleet panel
    fleet: "Fleet",
    noFleetRuns: "No Fleet runs",
    fleetWorkers: "Workers",
    fleetTasks: "Tasks",
    fleetReceipts: "Receipts",
    fleetStart: "Start",
    fleetStop: "Stop",
    fleetRestart: "Restart",
    fleetStatus: "Status",
    fleetAttempts: "Attempts",
    fleetScore: "Score",
    fleetViewReply: "View reply",
    fleetTaskInstructions: "Prompt",
    fleetNewFromRun: "New from this run",
    fleetNewFromRunHint: "Prefill the create dialog with this run's roles and tasks",
    fleetEvFilterIssues: "Issues",
    fleetEvFilterProgress: "Progress",
    fleetEvFilterAll: "All",
    fleetTaskFailure: "Failure",
    fleetEvRunCreated: "Run created",
    fleetEvRunStatus: "Run status",
    fleetEvEnqueued: "Task enqueued",
    fleetEvLeased: "Task leased",
    fleetEvTerminal: "Task ended",
    fleetEvReceipt: "Receipt",
    fleetEvHeartbeat: "Heartbeat",
    fleetEvAlert: "Alert",
    fleetInterrupt: "Interrupt",
    fleetStEnqueued: "Enqueued",
    fleetStLeased: "Leased",
    fleetStCompleted: "Completed",
    fleetStFailed: "Failed",
    fleetStCancelled: "Cancelled",
    fleetStUnknown: "Unknown",
    fleetStOnline: "Online",
    fleetStBusy: "Busy",
    fleetStOffline: "Offline",
    fleetStUnhealthy: "Unhealthy",
    fleetStDraining: "Draining",
    fleetStRetired: "Retired",
    fleetStQueued: "Queued",
    fleetStPending: "Pending",
    fleetStRunning: "Running",
    fleetStPaused: "Paused",
    fleetStEnqueuedHint: "Queued — waiting for a worker to pick it up",
    fleetLatestMessage: "Latest message",
    fleetNoWorkers: "No workers yet",
    fleetNoTasks: "No tasks yet",
    fleetNoReceipts: "No receipts yet",
    fleetRunId: "Run",
    fleetTaskCount: "Tasks",
    fleetWorkerCount: "Workers",
    fleetCreate: "Create Fleet run",
    fleetCreateDesc: "Launch several agents in parallel. Step 1: fill in basics · Step 2: declare roles (who does it) · Step 3: add tasks and pick a role for each (what to do).",
    fleetCreateName: "Name (optional)",
    fleetCreateWorkflowId: "Workflow ID",
    fleetCreateMaxWorkers: "Max workers (optional)",
    fleetCreateRoles: "Roles",
    fleetCreateRolesHint: "Optional: which agent profile this role uses",
    fleetProfileNone: "Default (no profile)",
    fleetCreateStartNow: "Start immediately after creation",
    fleetCreateBasics: "Basics",
    fleetCreateBasicsDesc: "Give this run an optional display name and a unique workflow ID.",
    fleetCreateRolesDesc: "Each role becomes one worker. The optional agent_profile selects which agent configuration backs the role.",
    fleetCreateTasksDesc: "Each task is assigned to one role. Every declared role must be used by at least one task.",
    fleetCreateTasks: "Tasks",
    fleetCreateAddRole: "Add role",
    fleetCreateAddTask: "Add task",
    fleetCreateTaskId: "Task ID",
    fleetCreateTaskName: "Task name",
    fleetCreateTaskRole: "Role",
    fleetCreateTaskObjective: "Objective (optional)",
    fleetCreateTaskInstructions: "Instructions",
    fleetCreateRemove: "Remove",
    fleetCreateSubmit: "Create run",
    fleetCreateTokenError: "must be a simple ASCII token",
    fleetCreateDuplicate: "is used more than once in this run",
    // Goal control plane
    goalStatus: "Status",
    goalBudget: "Budget",
    goalTokensUsed: "Tokens used",
    goalTimeUsed: "Time used",
    goalContinuations: "Continuations",
    goalSet: "Set goal",
    goalEdit: "Edit",
    goalComplete: "Complete",
    goalBlock: "Block",
    goalDelete: "Delete",
    goalObjectivePlaceholder: "Describe the objective…",
    goalNoGoal: "No goal set for this thread",
    goalTokenBudgetLabel: "Token budget (optional)",
    goalCreatedAt: "Created",
    goalBudgetTooltip: "Tokens consumed vs. the goal's token budget",
    goalTokensUsedTooltip: "Total tokens consumed while pursuing this goal",
    goalTimeUsedTooltip: "Total active time spent pursuing this goal",
    goalContinuationsTooltip: "How many times this goal has been continued",
    goalBudgetExceeded: "over budget",
    ...overrides,
  };
}
